name = "LAMBS RPG - SOG"
prefix = "rpg_sog"
author = "Esmeray"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README*.md",     # Translated READMEs get moved to root in a hook (virtual file system)
    "AUTHORS.txt",
    "LICENSE",
    "lambs_logo.paa",
    "meta.cpp",
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997",  # CBA_A3
    "1779063631", # Zeus Enhanced
    "623475643",  # 3den Enhanced
    "2369477168", # Advanced Dev Tools
]
dlc = ["VN"]
